<?php

class PluginDev_ModuleDev extends Module {

    protected $sPrefixText = '';
    protected $sPostfixText = '';

    public function Init() {

        $this->sPrefixText =
            '<?php' . PHP_EOL
            . '/*' . PHP_EOL
            . ' * This is autogenerated file' . PHP_EOL
            . ' */' . PHP_EOL;
        $this->sPostfixText = PHP_EOL . '// EOF';
    }

    public function Shutdown() {

        if (C::Get('plugin.dev.class_aliases.generate')) {
            $sDir = C::Get('plugin.dev.class_aliases.dir');
            if (F::File_CheckDir($sDir)) {
                $aAliases = Loader::GetAliases();
                $aAliasDefines = array();
                foreach($aAliases as $sAlias => $aInfo) {
                    $aAliasDefines[] = PHP_EOL . "class $sAlias extends {$aInfo['original']} { };";
                }
                $sAliasText = $this->sPrefixText . join(PHP_EOL, $aAliasDefines) . PHP_EOL . $this->sPostfixText;
                F::File_PutContents($sDir . 'Aliases.php', $sAliasText);
            }
        }
    }

}

// EOF